on:
  push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GMT_NPM_TOKEN: ${{ secrets.GMT_NPM_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - run: yarn
      env:
        NPM_TOKEN: ${{ secrets.GMT_NPM_TOKEN }}
    - run: yarn build
